### ISSUE TITLE
로직에서 변수를 선언하는 위치

### ISSUE THREAD

**Issue by Kirade** [8percent/styleguide#6]
```
----------------------------------------
# 변수를 처음에 정의하자
foo = []
bar = 'test'

for i in range(10):
    foo.append(i)
----------------------------------------
# 변수가 사용되는 시점에 정의하자
bar = 'test'

foo = []
for i in range(10):
    foo.append(i)
----------------------------------------
```

**Comment by silry** [comment]
https://codereview.stackexchange.com/questions/6283/variable-declaration-closer-to-usage-vs-declaring-at-the-top-of-method 이곳의 토론을 봤는데요, 대부분 사용되는 시점에 정의하는 것을 선호하네요. 
정리하면
1. "The scope of local variables should always be as minimal as possible.": 지역변수가 최소한의 스코프들에서 공유되도록 하자
2. 어떻게 변수가 쓰일 것인지 암시할 수 있다
3. 처음 변수가 사용되는 곳을 더 쉽게 파악할 수 있다
4. 리팩토링할 때 변수가 어떤 곳에서 사용되는지 쉽게 알 수 있다
