### ISSUE TITLE
테스트 작성법 개선

### ISSUE THREAD

**Issue by silry** [8percent/styleguide#7]
[테스트](https://github.com/8percent/styleguide#%ED%85%8C%EC%8A%A4%ED%8A%B8) 목차에 들어갈 내용을 고민하고 있습니다.

## 테스트 이름 작성법
- 어떤 트리거와 관련된 테스트 또는 한 모듈 내에서 테스트를 찾을때 테스트명의 의도가 일관적이지 않으면 그 테스트가 시도하려는 것이 무엇인지 알기 어려울 수 있습니다.
    - 테스트에 영어-한글명이 혼재되어 어떤 경우에 대한 테스트를 찾기 어렵습니다.
        - 영어보다는 한글로 작성하면 좋을 것 같습니다. ex: "test_자동투자_켜기"
    - test_메서드명_케이스 처럼 이름짓기
        - 메서드명으로 관련 케이스를 모두 찾을 수 있어서 좋습니다 (from 재영님)
        - 시나리오 테스트에서는 docstring에 관련 메서드를 넣어주는 것도 방법이지 않을까요?
    - 테스트명을 더 일관적이게 만들기
        - test_어떤_시나리오, test_어떤_메서드, test_어떤_상태일_경우 등이 가능한 상태입니다. 하지만 테스트_어떤_시나리오 와 같은 이름을 쓰면서 어떤 메서드만 assert하는 경우도 있는데, 이 경우에는 side effect가 잘 테스트되고 있는지 알기 어렵습니다. 같은 시나리오를 처리하려는 테스트가 분산/중복되어 짜일 수도 있습니다.
        - test_unit_메서드_어떤_상태_테스트, test_scenario_어떤_시나리오 처럼 구분하면 어떨까요?
    - 테스트 단위: 유닛테스트와 시나리오 테스트를 별도로 관리하면 어떨까요?
        - 메서드를 추가하고 그 메서드만을 위한 테스트를 만들 때도 있는데, 시나리오 테스트를 관리해서 메서드를 추가하면 해당 시나리오 테스트에 간단히 추가할 수 있도록 implication, side effect를 테스트하는 것이 좋을 것 같습니다. 
        - 히스토리 관리 역할도 수행해 줄 수 있을 것으로 기대합니다.

## Mock
- 여러 방법이 혼재되어 있습니다. 개선이 가능할 것 같습니다.

데코레이터를 사용하는 경우는 다음과 같습니다.
1. 테스트 클래스에 씌우기
2. 개별 테스트 메서드에 씌우기

어떤 테스트 클래스의 대부분의 개별 테스트에 공통된 mock이 필요한 경우에는 mock_메서드 = mock.patch('경로')를 사용합니다. 다음의 경우에 해당합니다. [참고](https://stackoverflow.com/questions/43594519/testing-in-django-what-are-differences-between-setupclass-setuptestdata-and-se)
1. setUp에 넣기
- 보통 .assert_called() 와 같이 메서드의 호출 여부를 검사할 때 공유된 메서드를 사용하지 않기 위해 사용합니다.
2. setUpTestData 또는 setUpClass에 넣기
- 보통 무거운 작동을 하거나 의존성을 갖는 메서드가 해당 동작을 시행하지 않도록 하기 위해 사용합니다. 

## fixture 선언
- 모델의 실제 값들을 fixture로 추출해 테스트해야 하는 경우가 존재합니다.
- ./manage.py dumpdata --format _ --indent _ -o _.json app.model

## Assert 
- assertFalse(mocked_method.called) <-> mocked_method.assert_called_once() 또는 .assert_called_with()

**Comment by Kirade** [comment]
저는 test_ 뒤에 붙는 명칭이 메서드명이였으면 좋겠습니다. 이렇게 해두면 IDE 에서 해당 메서드에 대한 테스트를 찾아주어 리팩토링이 쉽습니다. 
그래서 저는 `test_auto_invest_자동투자끄기`와 같이 메서드명을 쓰고 한글로 설명을 남기는 편입니다.
